package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Release'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Release")
    name = "Release"

    vcs {
        root(RelativeId("HttpsGithubComUygarSenocakkTeamcityExampleGit"))
    }

    steps {
        maven {
            name = "Clean"
            goals = "release:clean"
        }
        script {
            scriptContent = """
                git config --global user.email "temacity@dbo.com"
                git config --global user.name "Teamcity"
            """.trimIndent()
        }
        maven {
            name = "Release"
            goals = "release:prepare"
        }
    }
}))

