package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Test'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("TeamcityTemplate"))
    id("Test")
    name = "Test"

    vcs {
        root(DslContext.settingsRoot)
    }

    features {
        commitStatusPublisher {
            id = "BUILD_EXT_3"
            vcsRootExtId = "${DslContext.settingsRoot.id}"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = password {
                    userName = "uygare@gmail.com"
                    password = "credentialsJSON:6fd45833-c994-44f8-a611-0073690f8d1a"
                }
            }
        }
    }
}))

