package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComUygarSenocakkTeamcityExampleGitRefsHeadsMain1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComUygarSenocakkTeamcityExampleGitRefsHeadsMain1")
    name = "https://github.com/UygarSenocakk/TeamcityExample.git#refs/heads/main (1)"
    url = "https://github.com/UygarSenocakk/TeamcityExample.git"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "uygare@gmail.com"
        password = "credentialsJSON:6fd45833-c994-44f8-a611-0073690f8d1a"
    }
}))

